# Generated by Django 4.2.7 on 2023-11-28 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0003_alter_searchhistory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchhistory",
            options={},
        ),
    ]
