# Generated by Django 4.2.7 on 2023-11-29 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0005_alter_searchhistory_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchhistory",
            old_name="search_query",
            new_name="query",
        ),
    ]
