# Generated by Django 4.2.7 on 2023-11-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0009_alter_searchhistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchhistory",
            name="count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
