# Generated by Django 4.2.7 on 2023-12-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0011_alter_searchhistory_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchhistory",
            name="count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
