# Generated by Django 4.2.5 on 2023-11-22 19:22

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userID', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('shoeType', models.IntegerField()),
                ('clothType', multiselectfield.db.fields.MultiSelectField(choices=[('street', '스트릿'), ('minimal', '미니멀'), ('casual', '캐주얼'), ('dandy', '댄디'), ('vintage', '빈티지'), ('urban', '모던'), ('classic', '클래식'), ('feminine', '페미닌'), ('spoty', '스포티'), ('retro', '레트로')], max_length=20)),
                ('skinType', multiselectfield.db.fields.MultiSelectField(choices=[('oily', '지성'), ('acne', '여드름'), ('combination', '복합성'), ('dry', '건성'), ('sensitive', '민감성'), ('normal', '보통')], max_length=20)),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='SignUp.user')),
            ],
        ),
    ]
