# Generated by Django 4.2.7 on 2023-11-22 23:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('feminine', '페미닌'), ('retro', '레트로'), ('classic', '클래식'), ('vintage', '빈티지'), ('urban', '모던'), ('casual', '캐주얼'), ('dandy', '댄디'), ('minimal', '미니멀'), ('spoty', '스포티'), ('street', '스트릿')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dry', '건성'), ('combination', '복합성'), ('normal', '보통'), ('acne', '여드름'), ('oily', '지성'), ('sensitive', '민감성')], max_length=20),
        ),
    ]
