# Generated by Django 4.2.7 on 2023-11-21 07:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0002_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('feminine', '페미닌'), ('minimal', '미니멀'), ('vintage', '빈티지'), ('dandy', '댄디'), ('casual', '캐주얼'), ('retro', '레트로'), ('street', '스트릿'), ('modern', '모던'), ('spoty', '스포티')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('combination', '복합성'), ('oily', '지성'), ('acne', '여드름'), ('dry', '건성'), ('sensitive', '민감성'), ('normal', '보통')], max_length=20),
        ),
    ]
