# Generated by Django 4.2.5 on 2023-11-23 15:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0002_alter_userdata_clothtype_alter_userdata_skintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('feminine', '페미닌'), ('dandy', '댄디'), ('classic', '클래식'), ('spoty', '스포티'), ('retro', '레트로'), ('casual', '캐주얼'), ('minimal', '미니멀'), ('vintage', '빈티지'), ('street', '스트릿'), ('urban', '모던')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('normal', '보통'), ('dry', '건성'), ('combination', '복합성'), ('oily', '지성'), ('acne', '여드름'), ('sensitive', '민감성')], max_length=20),
        ),
    ]
