# Generated by Django 4.2.7 on 2023-11-21 07:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0003_alter_userdata_clothtype_alter_userdata_skintype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ID',
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dandy', '댄디'), ('feminine', '페미닌'), ('casual', '캐주얼'), ('spoty', '스포티'), ('retro', '레트로'), ('minimal', '미니멀'), ('street', '스트릿'), ('modern', '모던'), ('vintage', '빈티지')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sensitive', '민감성'), ('normal', '보통'), ('dry', '건성'), ('acne', '여드름'), ('combination', '복합성'), ('oily', '지성')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
