# Generated by Django 4.2.5 on 2023-11-23 15:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0003_alter_userdata_clothtype_alter_userdata_skintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('spoty', '스포티'), ('classic', '클래식'), ('minimal', '미니멀'), ('dandy', '댄디'), ('street', '스트릿'), ('retro', '레트로'), ('vintage', '빈티지'), ('feminine', '페미닌'), ('casual', '캐주얼'), ('urban', '모던')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('normal', '보통'), ('sensitive', '민감성'), ('acne', '여드름'), ('combination', '복합성'), ('dry', '건성'), ('oily', '지성')], max_length=20),
        ),
    ]
