# Generated by Django 4.2.7 on 2023-11-21 08:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0004_remove_user_id_alter_user_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('feminine', '페미닌'), ('street', '스트릿'), ('retro', '레트로'), ('vintage', '빈티지'), ('casual', '캐주얼'), ('minimal', '미니멀'), ('modern', '모던'), ('dandy', '댄디'), ('spoty', '스포티')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sensitive', '민감성'), ('dry', '건성'), ('combination', '복합성'), ('normal', '보통'), ('oily', '지성'), ('acne', '여드름')], max_length=20),
        ),
    ]
