# Generated by Django 4.2.5 on 2023-11-23 15:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0005_alter_userdata_clothtype_alter_userdata_skintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('spoty', '스포티'), ('street', '스트릿'), ('vintage', '빈티지'), ('casual', '캐주얼'), ('minimal', '미니멀'), ('retro', '레트로'), ('classic', '클래식'), ('urban', '모던'), ('feminine', '페미닌'), ('dandy', '댄디')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('acne', '여드름'), ('sensitive', '민감성'), ('dry', '건성'), ('combination', '복합성'), ('normal', '보통'), ('oily', '지성')], max_length=20),
        ),
    ]
