# Generated by Django 4.2.7 on 2023-11-21 08:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0006_alter_userdata_clothtype_alter_userdata_skintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('spoty', '스포티'), ('retro', '레트로'), ('modern', '모던'), ('casual', '캐주얼'), ('vintage', '빈티지'), ('dandy', '댄디'), ('feminine', '페미닌'), ('street', '스트릿'), ('minimal', '미니멀')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('normal', '보통'), ('acne', '여드름'), ('sensitive', '민감성'), ('oily', '지성'), ('combination', '복합성'), ('dry', '건성')], max_length=20),
        ),
    ]
