# Generated by Django 4.2.7 on 2023-11-21 08:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0007_alter_user_id_alter_userdata_clothtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('feminine', '페미닌'), ('street', '스트릿'), ('dandy', '댄디'), ('minimal', '미니멀'), ('casual', '캐주얼'), ('retro', '레트로'), ('spoty', '스포티'), ('modern', '모던'), ('vintage', '빈티지')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sensitive', '민감성'), ('combination', '복합성'), ('dry', '건성'), ('normal', '보통'), ('oily', '지성'), ('acne', '여드름')], max_length=20),
        ),
    ]
