# Generated by Django 4.2.5 on 2023-11-23 15:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0007_alter_userdata_clothtype_alter_userdata_skintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('classic', '클래식'), ('street', '스트릿'), ('spoty', '스포티'), ('urban', '모던'), ('vintage', '빈티지'), ('retro', '레트로'), ('feminine', '페미닌'), ('minimal', '미니멀'), ('dandy', '댄디'), ('casual', '캐주얼')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('acne', '여드름'), ('normal', '보통'), ('sensitive', '민감성'), ('combination', '복합성'), ('dry', '건성'), ('oily', '지성')], max_length=20),
        ),
    ]
