# Generated by Django 4.2.7 on 2023-11-21 08:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0008_alter_userdata_clothtype_alter_userdata_skintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dandy', '댄디'), ('vintage', '빈티지'), ('casual', '캐주얼'), ('modern', '모던'), ('retro', '레트로'), ('street', '스트릿'), ('feminine', '페미닌'), ('minimal', '미니멀'), ('spoty', '스포티')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('combination', '복합성'), ('sensitive', '민감성'), ('oily', '지성'), ('acne', '여드름'), ('dry', '건성'), ('normal', '보통')], max_length=20),
        ),
    ]
