# Generated by Django 4.2.7 on 2023-11-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0009_alter_user_id_alter_userdata_clothtype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
