# Generated by Django 4.2.7 on 2023-11-21 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0010_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('shoeType', models.IntegerField()),
                ('clothType', multiselectfield.db.fields.MultiSelectField(choices=[('casual', '캐주얼'), ('modern', '모던'), ('vintage', '빈티지'), ('feminine', '페미닌'), ('spoty', '스포티'), ('street', '스트릿'), ('minimal', '미니멀'), ('dandy', '댄디'), ('retro', '레트로')], max_length=20)),
                ('skinType', multiselectfield.db.fields.MultiSelectField(choices=[('combination', '복합성'), ('normal', '보통'), ('dry', '건성'), ('oily', '지성'), ('sensitive', '민감성'), ('acne', '여드름')], max_length=20)),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
