# Generated by Django 4.2.7 on 2023-11-15 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False)),
                ('tagName', models.TextField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='boardType',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='like_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='board',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.TextField(max_length=25),
        ),
        migrations.CreateModel(
            name='TagBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardID', models.ForeignKey(db_column='boardID', on_delete=django.db.models.deletion.CASCADE, to='community.board')),
                ('tagID', models.ForeignKey(db_column='tagID', on_delete=django.db.models.deletion.CASCADE, to='community.tag')),
            ],
        ),
        migrations.CreateModel(
            name='StyleRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(auto_now_add=True)),
                ('boardID_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardID_1', to='community.board')),
                ('boardID_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardID_2', to='community.board')),
                ('boardID_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardID_3', to='community.board')),
            ],
        ),
        migrations.CreateModel(
            name='ReportBoardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardID', models.ForeignKey(db_column='boardID', on_delete=django.db.models.deletion.CASCADE, to='community.board')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('boardID', models.ForeignKey(db_column='boardID', on_delete=django.db.models.deletion.CASCADE, to='community.board')),
                ('receiveID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiveID', to=settings.AUTH_USER_MODEL)),
                ('sendID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardID', models.ForeignKey(db_column='boardID', on_delete=django.db.models.deletion.CASCADE, to='community.board')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('nickname', models.TextField()),
                ('boardID', models.ForeignKey(db_column='boardID', on_delete=django.db.models.deletion.CASCADE, to='community.board')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
