# Generated by Django 4.2.7 on 2023-11-26 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagName',
            fields=[
                ('tagID', models.BigAutoField(primary_key=True, serialize=False)),
                ('tagName', models.TextField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='board',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tagboard',
            name='boardID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.board'),
        ),
        migrations.AlterField(
            model_name='tagboard',
            name='tagID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.tagname'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
