# Generated by Django 4.2.7 on 2023-11-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_tag_board_boardtype_board_datetime_board_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='like',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiveID',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sendID',
        ),
        migrations.RemoveField(
            model_name='reportboardlist',
            name='userID',
        ),
    ]
