# Generated by Django 4.2.5 on 2023-11-23 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('shoeType', models.IntegerField()),
                ('clothType', multiselectfield.db.fields.MultiSelectField(choices=[('classic', '클래식'), ('street', '스트릿'), ('spoty', '스포티'), ('urban', '모던'), ('vintage', '빈티지'), ('retro', '레트로'), ('feminine', '페미닌'), ('minimal', '미니멀'), ('dandy', '댄디'), ('casual', '캐주얼')], max_length=20)),
                ('skinType', multiselectfield.db.fields.MultiSelectField(choices=[('acne', '여드름'), ('normal', '보통'), ('sensitive', '민감성'), ('combination', '복합성'), ('dry', '건성'), ('oily', '지성')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
    ]
