# Generated by Django 4.2.7 on 2023-11-28 15:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('retro', '레트로'), ('feminine', '페미닌'), ('urban', '모던'), ('casual', '캐주얼'), ('street', '스트릿'), ('classic', '클래식'), ('dandy', '댄디'), ('spoty', '스포티'), ('vintage', '빈티지'), ('minimal', '미니멀')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('combination', '복합성'), ('dry', '건성'), ('oily', '지성'), ('normal', '보통'), ('acne', '여드름'), ('sensitive', '민감성')], max_length=20),
        ),
    ]
