# Generated by Django 4.2.5 on 2023-11-24 18:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('spoty', '스포티'), ('retro', '레트로'), ('feminine', '페미닌'), ('street', '스트릿'), ('minimal', '미니멀'), ('vintage', '빈티지'), ('dandy', '댄디'), ('casual', '캐주얼'), ('classic', '클래식'), ('urban', '모던')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('oily', '지성'), ('dry', '건성'), ('sensitive', '민감성'), ('combination', '복합성'), ('normal', '보통'), ('acne', '여드름')], max_length=20),
        ),
    ]
