# Generated by Django 4.2.5 on 2023-11-25 17:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userdata_clothtype_alter_userdata_skintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('retro', '레트로'), ('urban', '모던'), ('spoty', '스포티'), ('minimal', '미니멀'), ('dandy', '댄디'), ('feminine', '페미닌'), ('street', '스트릿'), ('vintage', '빈티지'), ('classic', '클래식'), ('casual', '캐주얼')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='shoeType',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('normal', '보통'), ('dry', '건성'), ('acne', '여드름'), ('combination', '복합성'), ('oily', '지성'), ('sensitive', '민감성')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
