<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-11-27 19:01
=======
# Generated by Django 4.2.7 on 2023-11-27 18:17
>>>>>>> 6ab391c2314f14b6dcbfc93905d34636fa0ee441

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('accounts', '0003_alter_userdata_clothtype_alter_userdata_height_and_more'),
=======
    dependencies = [
        ("accounts", "0003_alter_userdata_clothtype_alter_userdata_height_and_more"),
>>>>>>> 6ab391c2314f14b6dcbfc93905d34636fa0ee441
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('minimal', '미니멀'), ('retro', '레트로'), ('classic', '클래식'), ('dandy', '댄디'), ('feminine', '페미닌'), ('urban', '모던'), ('street', '스트릿'), ('vintage', '빈티지'), ('casual', '캐주얼'), ('spoty', '스포티')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('combination', '복합성'), ('acne', '여드름'), ('dry', '건성'), ('normal', '보통'), ('oily', '지성'), ('sensitive', '민감성')], max_length=20),
=======
            model_name="userdata",
            name="clothType",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("minimal", "미니멀"),
                    ("feminine", "페미닌"),
                    ("classic", "클래식"),
                    ("retro", "레트로"),
                    ("vintage", "빈티지"),
                    ("street", "스트릿"),
                    ("casual", "캐주얼"),
                    ("urban", "모던"),
                    ("dandy", "댄디"),
                    ("spoty", "스포티"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="skinType",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("normal", "보통"),
                    ("oily", "지성"),
                    ("dry", "건성"),
                    ("sensitive", "민감성"),
                    ("combination", "복합성"),
                    ("acne", "여드름"),
                ],
                max_length=20,
            ),
>>>>>>> 6ab391c2314f14b6dcbfc93905d34636fa0ee441
        ),
    ]
