# Generated by Django 4.2.7 on 2023-12-01 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userdata_image_alter_userdata_clothtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='skinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal', models.BooleanField(default=True)),
                ('dry', models.BooleanField(default=False)),
                ('oily', models.BooleanField(default=False)),
                ('combination', models.BooleanField(default=False)),
                ('sensitive', models.BooleanField(default=False)),
                ('acne', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skintype',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='clothType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modern', models.BooleanField(default=True)),
                ('Feminine', models.BooleanField(default=False)),
                ('Dandy', models.BooleanField(default=False)),
                ('Retro', models.BooleanField(default=False)),
                ('Minimal', models.BooleanField(default=False)),
                ('Casual', models.BooleanField(default=False)),
                ('Street', models.BooleanField(default=False)),
                ('Sporty', models.BooleanField(default=False)),
                ('Urban', models.BooleanField(default=False)),
                ('Classic', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clothtype',
            },
        ),
    ]
