# Generated by Django 4.2.5 on 2023-11-25 18:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userdata_clothtype_alter_userdata_skintype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('classic', '클래식'), ('street', '스트릿'), ('urban', '모던'), ('minimal', '미니멀'), ('spoty', '스포티'), ('retro', '레트로'), ('vintage', '빈티지'), ('dandy', '댄디'), ('casual', '캐주얼'), ('feminine', '페미닌')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('acne', '여드름'), ('sensitive', '민감성'), ('dry', '건성'), ('combination', '복합성'), ('normal', '보통'), ('oily', '지성')], max_length=20),
        ),
    ]
