# Generated by Django 4.2.7 on 2023-12-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_skintype_message_clothtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothtype',
            name='Simple',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clothtype',
            name='Modern',
            field=models.BooleanField(default=False),
        ),
    ]
