<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-11-26 15:18
=======
# Generated by Django 4.2.7 on 2023-11-26 16:05
>>>>>>> add7c04bfea4e57a3b10f7ba98a19f1ea288bff9

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        ("accounts", "0006_alter_userdata_clothtype_alter_userdata_skintype"),
=======

    dependencies = [
        ('accounts', '0006_alter_userdata_clothtype_alter_userdata_skintype'),
>>>>>>> add7c04bfea4e57a3b10f7ba98a19f1ea288bff9
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="userdata",
            name="clothType",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("spoty", "스포티"),
                    ("feminine", "페미닌"),
                    ("casual", "캐주얼"),
                    ("street", "스트릿"),
                    ("vintage", "빈티지"),
                    ("minimal", "미니멀"),
                    ("dandy", "댄디"),
                    ("retro", "레트로"),
                    ("urban", "모던"),
                    ("classic", "클래식"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="skinType",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("oily", "지성"),
                    ("acne", "여드름"),
                    ("dry", "건성"),
                    ("combination", "복합성"),
                    ("normal", "보통"),
                    ("sensitive", "민감성"),
                ],
                max_length=20,
            ),
=======
            model_name='userdata',
            name='clothType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('urban', '모던'), ('retro', '레트로'), ('casual', '캐주얼'), ('classic', '클래식'), ('vintage', '빈티지'), ('spoty', '스포티'), ('dandy', '댄디'), ('street', '스트릿'), ('minimal', '미니멀'), ('feminine', '페미닌')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skinType',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('acne', '여드름'), ('combination', '복합성'), ('oily', '지성'), ('normal', '보통'), ('sensitive', '민감성'), ('dry', '건성')], max_length=20),
>>>>>>> add7c04bfea4e57a3b10f7ba98a19f1ea288bff9
        ),
    ]
