# Generated by Django 4.2.7 on 2023-11-28 15:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_userdata_clothtype_alter_userdata_skintype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="clothType",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("dandy", "댄디"),
                    ("classic", "클래식"),
                    ("retro", "레트로"),
                    ("casual", "캐주얼"),
                    ("street", "스트릿"),
                    ("spoty", "스포티"),
                    ("minimal", "미니멀"),
                    ("feminine", "페미닌"),
                    ("vintage", "빈티지"),
                    ("urban", "모던"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="skinType",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("oily", "지성"),
                    ("dry", "건성"),
                    ("sensitive", "민감성"),
                    ("acne", "여드름"),
                    ("combination", "복합성"),
                    ("normal", "보통"),
                ],
                max_length=20,
            ),
        ),
    ]
