<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-11-27 19:01
=======
# Generated by Django 4.2.7 on 2023-11-27 15:58
>>>>>>> 6ab391c2314f14b6dcbfc93905d34636fa0ee441

from django.db import migrations


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('Search', '0001_initial'),
=======
    dependencies = [
        ("Search", "0001_initial"),
>>>>>>> 6ab391c2314f14b6dcbfc93905d34636fa0ee441
    ]

    operations = [
        migrations.AlterModelOptions(
<<<<<<< HEAD
            name='searchhistory',
            options={'verbose_name': 'Search History', 'verbose_name_plural': 'Search Histories'},
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
=======
            name="searchhistory",
            options={
                "verbose_name": "Search History",
                "verbose_name_plural": "Search Histories",
            },
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Tag",
>>>>>>> 6ab391c2314f14b6dcbfc93905d34636fa0ee441
        ),
    ]
