# Generated by Django 4.2.7 on 2023-11-27 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchhistory",
            options={
                "verbose_name": "Search History",
                "verbose_name_plural": "Search Histories",
            },
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
