# Generated by Django 4.2.7 on 2023-11-29 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0005_alter_searchhistory_options"),
        ("Search", "0007_alter_searchhistory_options_and_more"),
    ]

    operations = []
