# Generated by Django 4.2.7 on 2023-11-29 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0008_merge_20231129_2134"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchhistory",
            options={"ordering": ["-searched_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="searchhistory",
            unique_together=set(),
        ),
    ]
