# Generated by Django 4.2.5 on 2023-12-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_image_photosave_before_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='boardID',
        ),
    ]
